BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "todo_items" (
	"id"	INTEGER NOT NULL UNIQUE,
	"text"	TEXT NOT NULL,
	"done"	INTEGER NOT NULL,
	"seqUpdate"	INTEGER NOT NULL,
	"folderId"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
